# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addressdaytimedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Daydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AQI', models.CharField(blank=True, max_length=16, null=True)),
                ('Primary', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u9996\u8981\u6c61\u67d3\u7269')),
                ('SO2', models.CharField(blank=True, max_length=16, null=True)),
                ('NO2', models.CharField(blank=True, max_length=16, null=True)),
                ('PM10', models.CharField(blank=True, max_length=16, null=True)),
                ('CO', models.CharField(blank=True, max_length=16, null=True)),
                ('O3', models.CharField(blank=True, max_length=16, null=True)),
                ('PM2_5', models.CharField(blank=True, max_length=16, null=True)),
                ('Time', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Dayindexdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AQI', models.CharField(max_length=16)),
                ('SO2', models.CharField(max_length=16)),
                ('NO2', models.CharField(max_length=16)),
                ('PM10', models.CharField(max_length=16)),
                ('CO', models.CharField(max_length=16)),
                ('O3', models.CharField(max_length=16)),
                ('PM2_5', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Daytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AQI_system.Addressdaytimedata', verbose_name='\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Daytimedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_0_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time0', to='AQI_system.Dayindexdata', verbose_name='0\u65f6')),
                ('time_10_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time10', to='AQI_system.Dayindexdata', verbose_name='10\u65f6')),
                ('time_11_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time11', to='AQI_system.Dayindexdata', verbose_name='11\u65f6')),
                ('time_12_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time12', to='AQI_system.Dayindexdata', verbose_name='12\u65f6')),
                ('time_13_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time13', to='AQI_system.Dayindexdata', verbose_name='13\u65f6')),
                ('time_14_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time14', to='AQI_system.Dayindexdata', verbose_name='14\u65f6')),
                ('time_15_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time15', to='AQI_system.Dayindexdata', verbose_name='15\u65f6')),
                ('time_16_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time16', to='AQI_system.Dayindexdata', verbose_name='16\u65f6')),
                ('time_17_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time17', to='AQI_system.Dayindexdata', verbose_name='17\u65f6')),
                ('time_18_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time18', to='AQI_system.Dayindexdata', verbose_name='18\u65f6')),
                ('time_19_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time19', to='AQI_system.Dayindexdata', verbose_name='19\u65f6')),
                ('time_1_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='AQI_system.Dayindexdata', verbose_name='1\u65f6')),
                ('time_20_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time20', to='AQI_system.Dayindexdata', verbose_name='20\u65f6')),
                ('time_21_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time21', to='AQI_system.Dayindexdata', verbose_name='21\u65f6')),
                ('time_22_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time22', to='AQI_system.Dayindexdata', verbose_name='22\u65f6')),
                ('time_23_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time23', to='AQI_system.Dayindexdata', verbose_name='23\u65f6')),
                ('time_2_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='AQI_system.Dayindexdata', verbose_name='2\u65f6')),
                ('time_3_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time3', to='AQI_system.Dayindexdata', verbose_name='3\u65f6')),
                ('time_4_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time4', to='AQI_system.Dayindexdata', verbose_name='4\u65f6')),
                ('time_5_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time5', to='AQI_system.Dayindexdata', verbose_name='5\u65f6')),
                ('time_6_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time6', to='AQI_system.Dayindexdata', verbose_name='6\u65f6')),
                ('time_7_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time7', to='AQI_system.Dayindexdata', verbose_name='7\u65f6')),
                ('time_8_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time8', to='AQI_system.Dayindexdata', verbose_name='8\u65f6')),
                ('time_9_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time9', to='AQI_system.Dayindexdata', verbose_name='9\u65f6')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add1', to='AQI_system.Daytimedata', verbose_name='\u6210\u90fd\u5e02'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add2', to='AQI_system.Daytimedata', verbose_name='\u541b\u5e73\u8857'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add3', to='AQI_system.Daytimedata', verbose_name='\u5927\u77f3\u897f\u8def'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add4', to='AQI_system.Daytimedata', verbose_name='\u6881\u5bb6\u5df7'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add5', to='AQI_system.Daytimedata', verbose_name='\u91d1\u6cc9\u4e24\u6cb3'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add6', to='AQI_system.Daytimedata', verbose_name='\u6c99\u6cb3\u6ee9'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add7', to='AQI_system.Daytimedata', verbose_name='\u4e09\u74e6\u7a91'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add8', to='AQI_system.Daytimedata', verbose_name='\u5341\u91cc\u5e97'),
        ),
        migrations.AddField(
            model_name='addressdaytimedata',
            name='address9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add9', to='AQI_system.Daytimedata', verbose_name='\u7075\u5ca9\u5c71'),
        ),
    ]
